### ISSUE TITLE
Handle user interactions when switching between visual/code editor

### ISSUE THREAD

**Issue by A-Karam20** [Ghaadyy/testing-platform#3]
## **The issue**  
There are two related problems when users switch between the visual and code editors:

1. **Adjust new/save buttons when in the visual editor**  
   - The "new" and "save" buttons in the visual editor may not functional correctly. Ensure these buttons adapt appropriately based on the editor mode.  

2. **Handle switching back and forth with errors in user code**  
   - When a user switches between the visual editor and code editor while their code has errors, the editor should handle this scenario. Currently, this may cause unexpected behavior.

**Comment by Ghaadyy** [comment]
This should be fixed.

**Comment by Ghaadyy** [comment]
> 1. Adjust new/save buttons when in the visual editor

It seems this has not been fixed yet with the previous PR.
